.gitignore
README.md
app.py
backend/__init__.py
backend/app.py
backend/modules/__init__.py
backend/modules/actions.py
backend/modules/ai_analyzer.py
backend/modules/attachment_analyzer.py
backend/modules/database.py
backend/modules/email_parser.py
backend/modules/header_analyzer.py
backend/modules/header_analyzer.pyes o     headers: dict[str, Any]
backend/modules/html_analyzer.py
backend/modules/report_generator.py
backend/modules/risk_engine.py
backend/modules/url_analyzer.py
backend/modules/url_analyzer.y
backend/web.py
frontend/.gitignore
frontend/.oxlintrc.json
frontend/README.md
frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/public/favicon.svg
frontend/public/icons.svg
frontend/src/App.css
frontend/src/App.jsx
frontend/src/assets/hero.png
frontend/src/assets/react.svg
frontend/src/assets/vite.svg
frontend/src/index.css
frontend/src/main.jsx
frontend/vite.config.js
requirements.txt
risk_test.json
static/app.js
static/style.css
templates/index.html
